### ISSUE TITLE
copycat?

### ISSUE THREAD

**Issue by Jonyk56** [ghostoblivion/GlitchForumDark#1]

**Comment by ghostoblivion** [comment]
This is in no way, shape or form a copycat.  If it does resemble any other existing theme, I am unaware of that.

**Comment by Jonyk56** [comment]
https://support.glitch.com/t/hey-free-darkmode/16888

**Comment by ghostoblivion** [comment]
That is in no way related to the theme I made.  
My theme was made by modifying the contents of [this](https://sjc3.discourse-cdn.com/business6/stylesheets/color_definitions_glitch_1_46b7c133dd45c8739e673e8a96de53901df0b200.css?__ws=support.glitch.com) file (from the forum source).


Compare the code.  You'll see a major difference in 
1. How they are made.
2. How they actually interact with the css.
3. How they look.
All of those are completely different.

**Comment by Jonyk56** [comment]
🤔  ok then, you win this round =P 


but mine still wins
